behaviors:
  DriveBehaviorCurve:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 12000
      learning_rate: 0.0002
      beta: 0.005
      epsilon: 0.2
      lambd: 0.89
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 10000
    time_horizon: 1000
    summary_freq: 1000
environment_parameters: # Now these are hopefully used
  ciriconf:
    curriculum:
      - name: Lesson0 # The '-' is important as this is a list
        completion_criteria:
          measure: progress
          behavior: DriveBehaviorCurve
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.06
        value: 1.0
      - name: Lesson1 # This is the start of the second lesson
        completion_criteria:
          measure: progress
          behavior: DriveBehaviorCurve
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.18
        value: 2.0
      - name: Lesson2 # This is the start of the second lesson
        completion_criteria:
          measure: progress
          behavior: DriveBehaviorCurve
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.30
        value: 3.0
      - name: Lesson3 # This is the start of the second lesson
        completion_criteria:
          measure: progress
          behavior: DriveBehaviorCurve
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.42
        value: 4.0
      - name: Lesson4 # This is the start of the second lesson
        completion_criteria:
          measure: progress
          behavior: DriveBehaviorCurve
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.54
        value: 5.0
      - name: Lesson5 # This is the start of the second lesson
        completion_criteria:
          measure: progress
          behavior: DriveBehaviorCurve
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.66
        value: 6.0
      - name: Lesson6 # This is the start of the second lesson
        completion_criteria:
          measure: progress
          behavior: DriveBehaviorCurve
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.78
        value: 7.0
      - name: Lesson7 # This is the start of the track lesson
        completion_criteria:
          measure: progress
          behavior: DriveBehaviorCurve
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.90
        value: 8.0