behaviors:
  DriveBehaviorStraight:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 12000
      learning_rate: 0.0003
      beta: 0.001
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 100000
    time_horizon: 1000
    summary_freq: 1000
  DriveBehaviorCurve:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 12000
      learning_rate: 0.0003
      beta: 0.001
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 1000000
    time_horizon: 1000
    summary_freq: 1000
environment_parameters: # These are not used right now
  straight:
    curriculum:
      - name: Lesson0 # The '-' is important as this is a list
        completion_criteria:
          measure: progress
          behavior: DriveBehavior
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.1
        value: 1.0
      - name: Lesson1 # This is the start of the second lesson
        completion_criteria:
          measure: progress
          behavior: DriveBehavior
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.3
        value: 1.0
  small_turn:
    curriculum:
      - name: Lesson0
        completion_criteria:
          measure: progress
          behavior: DriveBehavior3
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.1
        value: 1.5
      - name: Lesson1
        completion_criteria:
          measure: progress
          behavior: DriveBehavior3
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.3
        value: 2.0
  big_turn:
    curriculum:
      - name: Lesson0
        completion_criteria:
          measure: progress
          behavior: DriveBehavior2
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.1
        value: 1.5
      - name: Lesson1
        completion_criteria:
          measure: progress
          behavior: DriveBehavior2
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.3
        value: 2.0
